### PR TITLE
Replace string.split() with <str>.split()

### PR DESCRIPTION
**Pull request by robin-norwood**
string.split() does not exist in Python 3. **str**.split() exists in both Python 3 and Python 2.7.

### CODE REVIEW

**Comment by robin-norwood** [comment]
Any thoughts on merging this one?

**Comment by joseph-wortmann** [comment]
Sorry - got busy - doing it now for you

**Comment by robin-norwood** [comment]
Thanks!

**Comment by joseph-wortmann** [comment]
Done and done. Fully pulled through to master, version 0.1.9 uploaded to PyPI

**Pull request merged**
